

class Media_IDs:

    main_picture_id = 'AgACAgIAAxkBAAPJaUhdin9nxBOJX2xYjFpFEGVP7OcAAuwUaxvgKEBKNbyMq2KPF08BAAMCAAN5AAM2BA'

    navigator_main_id = 'AgACAgIAAxkBAAPSaUheO9JllGYPIX-zVnLBfXkzgxgAAvAUaxvgKEBKf68DgyHoVlYBAAMCAAN5AAM2BA'
    steps = [
        'AgACAgIAAxkBAAPUaUheQEaShdMbrNWvNbJ8YxOgXckAAvEUaxvgKEBKWwaPB5YUwXcBAAMCAAN5AAM2BA',
        'AgACAgIAAxkBAAPWaUheRBWAanqMNozwGo3y-2wmNmIAAvIUaxvgKEBK1ZZjG8T_dccBAAMCAAN5AAM2BA',
        'AgACAgIAAxkBAAPYaUheSNwohYocw1tcDLNJoptxj4YAAvMUaxvgKEBKvkKElaxx-lABAAMCAAN5AAM2BA',
        'AgACAgIAAxkBAAPaaUheS7cCFECJTfBJ6gmjubLuj9gAAvQUaxvgKEBK9aHfDlvXlv4BAAMCAAN5AAM2BA',
        'AgACAgIAAxkBAAPcaUheTxZwgvNRkJXC84pzYp6gjiQAAvUUaxvgKEBKXb0X7H1RLJgBAAMCAAN5AAM2BA',
        'AgACAgIAAxkBAAPeaUheVLF68Vuo9kggBgzkRqGHgRoAAvYUaxvgKEBKn9FzKTqLAAFHAQADAgADeQADNgQ',
        'AgACAgIAAxkBAAPgaUheWc4sKTfmuEoEyumVQpOa4wMAAvcUaxvgKEBKbmzRWG7gUe4BAAMCAAN5AAM2BA'
    ]
    

    

    

    # step_4_id = 'AgACAgIAAxkBAAPaaUheS7cCFECJTfBJ6gmjubLuj9gAAvQUaxvgKEBK9aHfDlvXlv4BAAMCAAN5AAM2BA'

    # step_5_id = 'AgACAgIAAxkBAAPcaUheTxZwgvNRkJXC84pzYp6gjiQAAvUUaxvgKEBKXb0X7H1RLJgBAAMCAAN5AAM2BA'

    # step_6_id = 'AgACAgIAAxkBAAPeaUheVLF68Vuo9kggBgzkRqGHgRoAAvYUaxvgKEBKn9FzKTqLAAFHAQADAgADeQADNgQ'

    # step_7_id = 'AgACAgIAAxkBAAPgaUheWc4sKTfmuEoEyumVQpOa4wMAAvcUaxvgKEBKbmzRWG7gUe4BAAMCAAN5AAM2BA'
